language: go

go:
  - 1.7

install:
  - go get .

script:
  - set -e
  - go vet .
  - go get ./singleton-runner-integration
  - singleton-runner-integration --etcd-version 3.0.9

notifications:
  - email: false
